// Склад временных данных для корректной работы верскти

const moviesData = [
  {
    country: "USA",
    director: "Quentin Jerome Tarantino",
    duration: 27,
    year: 1999,
    description: "Some fish text",
    image: "https://i.ibb.co/3yVn66s/pic-COLOR-pic.png",
    trailerLink: "https://i.ibb.co/3yVn66s/pic-COLOR-pic.png",
    nameRU: "В погоне за Бренкси",
    nameEN: "В погоне за Бренкси",
    thumbnail: "",
    movieId: Math.random(),
  },
  {
    country: "USA",
    director: "Quentin Jerome Tarantino",
    duration: 27,
    year: 1999,
    description: "Some fish text",
    image: "https://i.ibb.co/pbHSgLW/pic-COLOR-pic-4.png",
    trailerLink: "https://i.ibb.co/3yVn66s/pic-COLOR-pic.png",
    nameRU: "В погоне за Бренкси",
    nameEN: "В погоне за Бренкси",
    thumbnail: "",
    movieId: Math.random(),
  },
  {
    country: "USA",
    director: "Quentin Jerome Tarantino",
    duration: 27,
    year: 1999,
    description: "Some fish text",
    image: "https://i.ibb.co/tH9k0rj/pic-COLOR-pic-1.png",
    trailerLink: "https://i.ibb.co/3yVn66s/pic-COLOR-pic.png",
    nameRU: "В погоне за Бренкси",
    nameEN: "В погоне за Бренкси",
    thumbnail: "",
    movieId: Math.random(),
  },
  {
    country: "USA",
    director: "Quentin Jerome Tarantino",
    duration: 27,
    year: 1999,
    description: "Some fish text",
    image: "https://i.ibb.co/yQB94QS/pic-COLOR-pic-5.png",
    trailerLink: "https://i.ibb.co/3yVn66s/pic-COLOR-pic.png",
    nameRU: "В погоне за Бренкси",
    nameEN: "В погоне за Бренкси",
    thumbnail: "",
    movieId: Math.random(),
  },
  {
    country: "USA",
    director: "Quentin Jerome Tarantino",
    duration: 27,
    year: 1999,
    description: "Some fish text",
    image: "https://i.ibb.co/xF0sshg/pic-COLOR-pic-2.png",
    trailerLink: "https://i.ibb.co/3yVn66s/pic-COLOR-pic.png",
    nameRU: "В погоне за Бренкси",
    nameEN: "В погоне за Бренкси",
    thumbnail: "",
    movieId: Math.random(),
  },
  {
    country: "USA",
    director: "Quentin Jerome Tarantino",
    duration: 27,
    year: 1999,
    description: "Some fish text",
    image: "https://i.ibb.co/HHz6DDQ/pic-COLOR-pic-6.png",
    trailerLink: "https://i.ibb.co/3yVn66s/pic-COLOR-pic.png",
    nameRU: "В погоне за Бренкси",
    nameEN: "В погоне за Бренкси",
    thumbnail: "",
    movieId: Math.random(),
  },
  {
    country: "USA",
    director: "Quentin Jerome Tarantino",
    duration: 27,
    year: 1999,
    description: "Some fish text",
    image: "https://i.ibb.co/vVfTWmG/pic-COLOR-pic-3.png",
    trailerLink: "https://i.ibb.co/3yVn66s/pic-COLOR-pic.png",
    nameRU: "В погоне за Бренкси",
    nameEN: "В погоне за Бренкси",
    thumbnail: "",
    movieId: Math.random(),
  },
  {
    country: "USA",
    director: "Quentin Jerome Tarantino",
    duration: 27,
    year: 1999,
    description: "Some fish text",
    image: "https://i.ibb.co/jDXkcTF/pic-COLOR-pic-7.png",
    trailerLink: "https://i.ibb.co/3yVn66s/pic-COLOR-pic.png",
    nameRU: "В погоне за Бренкси",
    nameEN: "В погоне за Бренкси",
    thumbnail: "",
    movieId: Math.random(),
  },
  {
    country: "USA",
    director: "Quentin Jerome Tarantino",
    duration: 27,
    year: 1999,
    description: "Some fish text",
    image: "https://i.ibb.co/jDXkcTF/pic-COLOR-pic-7.png",
    trailerLink: "https://i.ibb.co/3yVn66s/pic-COLOR-pic.png",
    nameRU: "В погоне за Бренкси",
    nameEN: "В погоне за Бренкси",
    thumbnail: "",
    movieId: Math.random(),
  },
  {
    country: "USA",
    director: "Quentin Jerome Tarantino",
    duration: 27,
    year: 1999,
    description: "Some fish text",
    image: "https://i.ibb.co/jDXkcTF/pic-COLOR-pic-7.png",
    trailerLink: "https://i.ibb.co/3yVn66s/pic-COLOR-pic.png",
    nameRU: "В погоне за Бренкси",
    nameEN: "В погоне за Бренкси",
    thumbnail: "",
    movieId: Math.random(),
  },
  {
    country: "USA",
    director: "Quentin Jerome Tarantino",
    duration: 27,
    year: 1999,
    description: "Some fish text",
    image: "https://i.ibb.co/jDXkcTF/pic-COLOR-pic-7.png",
    trailerLink: "https://i.ibb.co/3yVn66s/pic-COLOR-pic.png",
    nameRU: "В погоне за Бренкси",
    nameEN: "В погоне за Бренкси",
    thumbnail: "",
    movieId: Math.random(),
  },
  {
    country: "USA",
    director: "Quentin Jerome Tarantino",
    duration: 27,
    year: 1999,
    description: "Some fish text",
    image: "https://i.ibb.co/jDXkcTF/pic-COLOR-pic-7.png",
    trailerLink: "https://i.ibb.co/3yVn66s/pic-COLOR-pic.png",
    nameRU: "В погоне за Бренкси",
    nameEN: "В погоне за Бренкси",
    thumbnail: "",
    movieId: Math.random(),
  },
];

const savedMoviesData = [
  {
    country: "USA",
    director: "Quentin Jerome Tarantino",
    duration: 27,
    year: 1999,
    description: "Some fish text",
    image: "https://i.ibb.co/HHz6DDQ/pic-COLOR-pic-6.png",
    trailerLink: "https://i.ibb.co/3yVn66s/pic-COLOR-pic.png",
    nameRU: "В погоне за Бренкси",
    nameEN: "В погоне за Бренкси",
    thumbnail: "",
    movieId: Math.random(),
  },
  {
    country: "USA",
    director: "Quentin Jerome Tarantino",
    duration: 27,
    year: 1999,
    description: "Some fish text",
    image: "https://i.ibb.co/vVfTWmG/pic-COLOR-pic-3.png",
    trailerLink: "https://i.ibb.co/3yVn66s/pic-COLOR-pic.png",
    nameRU: "В погоне за Бренкси",
    nameEN: "В погоне за Бренкси",
    thumbnail: "",
    movieId: Math.random(),
  },
  {
    country: "USA",
    director: "Quentin Jerome Tarantino",
    duration: 27,
    year: 1999,
    description: "Some fish text",
    image: "https://i.ibb.co/jDXkcTF/pic-COLOR-pic-7.png",
    trailerLink: "https://i.ibb.co/3yVn66s/pic-COLOR-pic.png",
    nameRU: "В погоне за Бренкси",
    nameEN: "В погоне за Бренкси",
    thumbnail: "",
    movieId: Math.random(),
  },
];

const userData = {
  name: "Григорий",
  email: "ghost1mod@gmail.com",
};

const temporaryData = {
  moviesData,
  savedMoviesData,
  userData,
};

export default temporaryData;
